-   id: eslint
    name: eslint
    entry: eslint
    language: node
    'types': [javascript]
    args: []
    require_serial: false
    additional_dependencies: ["eslint@8.0.1"]
    minimum_pre_commit_version: '0'
