-   id: eslint
    name: eslint
    description: ''
    entry: make client-eslint
    language: system
    'types': [javascript]
    args: []
    require_serial: false
    minimum_pre_commit_version: '0'
