-   id: eslint
    name: eslint
    description: ''
    entry: sh -c 'cd client && eslint'
    language: system
    'types': [javascript]
    args: []
    require_serial: false
    minimum_pre_commit_version: '0'
